# Generated by Django 5.2.8 on 2025-12-04 22:02

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "reservation_number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Numéro de réservation",
                    ),
                ),
                ("check_in_date", models.DateField(verbose_name="Date d'arrivée")),
                ("check_out_date", models.DateField(verbose_name="Date de départ")),
                (
                    "actual_check_in",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Check-in réel"
                    ),
                ),
                (
                    "actual_check_out",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Check-out réel"
                    ),
                ),
                (
                    "number_of_guests",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Nombre d'invités"
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(
                        blank=True,
                        help_text="Nom du client principal si différent de l'utilisateur",
                        max_length=200,
                        verbose_name="Nom de l'invité",
                    ),
                ),
                (
                    "guest_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de l'invité"
                    ),
                ),
                (
                    "guest_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone de l'invité"
                    ),
                ),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix par nuit (DZD)",
                    ),
                ),
                (
                    "total_nights",
                    models.PositiveIntegerField(verbose_name="Nombre de nuits"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Sous-total (DZD)"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Montant des taxes (DZD)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Montant de la remise (DZD)",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Montant total (DZD)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("CONFIRMED", "Confirmée"),
                            ("CHECKED_IN", "Check-in effectué"),
                            ("CHECKED_OUT", "Check-out effectué"),
                            ("CANCELLED", "Annulée"),
                            ("NO_SHOW", "Client absent"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(blank=True, verbose_name="Demandes spéciales"),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Notes internes"),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="Raison de l'annulation"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'annulation"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="rooms.room",
                        verbose_name="Chambre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
                "db_table": "reservations",
                "ordering": ["-created_at"],
            },
        ),
    ]
