# Generated by Django 5.2.8 on 2025-12-04 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de l'équipement"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("COMFORT", "Confort"),
                            ("TECHNOLOGY", "Technologie"),
                            ("BATHROOM", "Salle de bain"),
                            ("ENTERTAINMENT", "Divertissement"),
                            ("FOOD", "Restauration"),
                            ("SAFETY", "Sécurité"),
                            ("OTHER", "Autre"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nom de l'icône (ex: wifi, tv, ac)",
                        max_length=50,
                        verbose_name="Icône",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Équipement",
                "verbose_name_plural": "Équipements",
                "db_table": "amenities",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du type"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix de base (DZD)",
                    ),
                ),
                (
                    "max_occupancy",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Capacité maximale"
                    ),
                ),
                (
                    "size_sqm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Superficie (m²)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Type de chambre",
                "verbose_name_plural": "Types de chambres",
                "db_table": "room_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Numéro de chambre"
                    ),
                ),
                (
                    "floor",
                    models.IntegerField(
                        choices=[
                            (0, "Rez-de-chaussée"),
                            (1, "1er étage"),
                            (2, "2ème étage"),
                            (3, "3ème étage"),
                            (4, "4ème étage"),
                            (5, "5ème étage"),
                        ],
                        default=0,
                        verbose_name="Étage",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Disponible"),
                            ("OCCUPIED", "Occupée"),
                            ("MAINTENANCE", "En maintenance"),
                            ("CLEANING", "En nettoyage"),
                            ("OUT_OF_SERVICE", "Hors service"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "view_type",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Vue mer, Vue jardin, Vue ville",
                        max_length=50,
                        verbose_name="Type de vue",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "special_notes",
                    models.TextField(blank=True, verbose_name="Notes spéciales"),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="rooms/",
                        verbose_name="Image principale",
                    ),
                ),
                (
                    "custom_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Laisser vide pour utiliser le prix du type",
                        max_digits=10,
                        null=True,
                        verbose_name="Prix personnalisé (DZD)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rooms",
                        to="rooms.amenity",
                        verbose_name="Équipements",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rooms",
                        to="rooms.roomtype",
                        verbose_name="Type de chambre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chambre",
                "verbose_name_plural": "Chambres",
                "db_table": "rooms",
                "ordering": ["floor", "room_number"],
                "indexes": [
                    models.Index(
                        fields=["room_number"], name="rooms_room_nu_5c8eca_idx"
                    ),
                    models.Index(fields=["status"], name="rooms_status_ee4627_idx"),
                    models.Index(
                        fields=["room_type", "status"], name="rooms_room_ty_a7f7ec_idx"
                    ),
                ],
            },
        ),
    ]
