# Generated by Django 5.2.8 on 2025-12-04 22:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("RESERVATION_CREATED", "Réservation créée"),
                            ("RESERVATION_CONFIRMED", "Réservation confirmée"),
                            ("RESERVATION_CANCELLED", "Réservation annulée"),
                            ("RESERVATION_REMINDER", "Rappel de réservation"),
                            ("CHECK_IN_REMINDER", "Rappel de check-in"),
                            ("CHECK_OUT_REMINDER", "Rappel de check-out"),
                            ("PAYMENT_RECEIVED", "Paiement reçu"),
                            ("PAYMENT_FAILED", "Paiement échoué"),
                            ("REFUND_PROCESSED", "Remboursement effectué"),
                            ("INVOICE_GENERATED", "Facture générée"),
                            ("GENERAL", "Notification générale"),
                        ],
                        max_length=30,
                        verbose_name="Type de notification",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("IN_APP", "In-App"),
                            ("PUSH", "Push Notification"),
                        ],
                        default="EMAIL",
                        max_length=10,
                        verbose_name="Canal",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("SENT", "Envoyé"),
                            ("DELIVERED", "Délivré"),
                            ("FAILED", "Échoué"),
                            ("READ", "Lu"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Sujet")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "html_message",
                    models.TextField(blank=True, verbose_name="Message HTML"),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email destinataire"
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone destinataire"
                    ),
                ),
                (
                    "reservation_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="ID Réservation"
                    ),
                ),
                (
                    "payment_id",
                    models.UUIDField(blank=True, null=True, verbose_name="ID Paiement"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Envoyé le"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lu le"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de tentatives"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="notificatio_user_id_8ab96f_idx"
                    ),
                    models.Index(
                        fields=["notification_type", "status"],
                        name="notificatio_notific_21f913_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_e4c995_idx"
                    ),
                ],
            },
        ),
    ]
