// Notification Types
export const NOTIFICATION_TYPES = {
  RESERVATION_CREATED: 'RESERVATION_CREATED',
  RESERVATION_CONFIRMED: 'RESERVATION_CONFIRMED',
  RESERVATION_CANCELLED: 'RESERVATION_CANCELLED',
  RESERVATION_REMINDER: 'RESERVATION_REMINDER',
  CHECK_IN_REMINDER: 'CHECK_IN_REMINDER',
  CHECK_OUT_REMINDER: 'CHECK_OUT_REMINDER',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  REFUND_PROCESSED: 'REFUND_PROCESSED',
  INVOICE_GENERATED: 'INVOICE_GENERATED',
  GENERAL: 'GENERAL'
};

// Notification Status
export const NOTIFICATION_STATUS = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
  READ: 'READ'
};

// Notification Channels
export const NOTIFICATION_CHANNELS = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  IN_APP: 'IN_APP',
  PUSH: 'PUSH'
};

// Notification Type Labels (French)
export const NOTIFICATION_TYPE_LABELS = {
  [NOTIFICATION_TYPES.RESERVATION_CREATED]: 'Réservation créée',
  [NOTIFICATION_TYPES.RESERVATION_CONFIRMED]: 'Réservation confirmée',
  [NOTIFICATION_TYPES.RESERVATION_CANCELLED]: 'Réservation annulée',
  [NOTIFICATION_TYPES.RESERVATION_REMINDER]: 'Rappel de réservation',
  [NOTIFICATION_TYPES.CHECK_IN_REMINDER]: 'Rappel de check-in',
  [NOTIFICATION_TYPES.CHECK_OUT_REMINDER]: 'Rappel de check-out',
  [NOTIFICATION_TYPES.PAYMENT_RECEIVED]: 'Paiement reçu',
  [NOTIFICATION_TYPES.PAYMENT_FAILED]: 'Paiement échoué',
  [NOTIFICATION_TYPES.REFUND_PROCESSED]: 'Remboursement effectué',
  [NOTIFICATION_TYPES.INVOICE_GENERATED]: 'Facture générée',
  [NOTIFICATION_TYPES.GENERAL]: 'Notification générale'
};

// Colors for notification types
export const NOTIFICATION_COLORS = {
  [NOTIFICATION_TYPES.RESERVATION_CREATED]: 'blue',
  [NOTIFICATION_TYPES.RESERVATION_CONFIRMED]: 'green',
  [NOTIFICATION_TYPES.RESERVATION_CANCELLED]: 'red',
  [NOTIFICATION_TYPES.RESERVATION_REMINDER]: 'blue',
  [NOTIFICATION_TYPES.CHECK_IN_REMINDER]: 'blue',
  [NOTIFICATION_TYPES.CHECK_OUT_REMINDER]: 'blue',
  [NOTIFICATION_TYPES.PAYMENT_RECEIVED]: 'green',
  [NOTIFICATION_TYPES.PAYMENT_FAILED]: 'red',
  [NOTIFICATION_TYPES.REFUND_PROCESSED]: 'yellow',
  [NOTIFICATION_TYPES.INVOICE_GENERATED]: 'gray',
  [NOTIFICATION_TYPES.GENERAL]: 'gray'
};