# Generated by Django 5.2.8 on 2025-12-04 22:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reservations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Numéro de facture",
                    ),
                ),
                (
                    "billing_name",
                    models.CharField(max_length=200, verbose_name="Nom de facturation"),
                ),
                (
                    "billing_email",
                    models.EmailField(
                        max_length=254, verbose_name="Email de facturation"
                    ),
                ),
                (
                    "billing_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "billing_address",
                    models.TextField(blank=True, verbose_name="Adresse de facturation"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Sous-total (DZD)"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Montant des taxes (DZD)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Montant de la remise (DZD)",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Montant total (DZD)",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Montant payé (DZD)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("ISSUED", "Émise"),
                            ("PAID", "Payée"),
                            ("PARTIALLY_PAID", "Partiellement payée"),
                            ("OVERDUE", "En retard"),
                            ("CANCELLED", "Annulée"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'émission"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance"
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="reservations.reservation",
                        verbose_name="Réservation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "db_table": "invoices",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["invoice_number"], name="invoices_invoice_7778bc_idx"
                    ),
                    models.Index(
                        fields=["user", "status"], name="invoices_user_id_9940be_idx"
                    ),
                    models.Index(
                        fields=["status", "due_date"], name="invoices_status_73cf28_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Numéro de paiement",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant (DZD)"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="DZD", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Espèces"),
                            ("CREDIT_CARD", "Carte de crédit"),
                            ("DEBIT_CARD", "Carte de débit"),
                            ("STRIPE", "Stripe"),
                            ("PAYPAL", "PayPal"),
                            ("BANK_TRANSFER", "Virement bancaire"),
                            ("CCP", "CCP (Algérie Poste)"),
                        ],
                        max_length=20,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Acompte"),
                            ("FULL", "Paiement complet"),
                            ("PARTIAL", "Paiement partiel"),
                            ("REFUND", "Remboursement"),
                        ],
                        default="FULL",
                        max_length=10,
                        verbose_name="Type de paiement",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En traitement"),
                            ("COMPLETED", "Complété"),
                            ("FAILED", "Échoué"),
                            ("REFUNDED", "Remboursé"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de transaction externe (Stripe, PayPal, etc.)",
                        max_length=200,
                        verbose_name="ID de transaction",
                    ),
                ),
                (
                    "payment_gateway_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Réponse du gateway"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Traité le"
                    ),
                ),
                (
                    "refunded_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Montant remboursé (DZD)",
                    ),
                ),
                (
                    "refund_reason",
                    models.TextField(
                        blank=True, verbose_name="Raison du remboursement"
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Remboursé le"
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Traité par",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="reservations.reservation",
                        verbose_name="Réservation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "db_table": "payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["payment_number"], name="payments_payment_c27a96_idx"
                    ),
                    models.Index(
                        fields=["reservation", "status"],
                        name="payments_reserva_36243a_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="payments_user_id_1b771c_idx"
                    ),
                    models.Index(
                        fields=["transaction_id"], name="payments_transac_a1f824_idx"
                    ),
                ],
            },
        ),
    ]
